// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	BookingStatusCancelled BookingStatus = "cancelled"
	BookingStatusCompleted BookingStatus = "completed"
	BookingStatusConfirmed BookingStatus = "confirmed"
	BookingStatusOngoing   BookingStatus = "ongoing"
	BookingStatusPending   BookingStatus = "pending"
)

// Defines values for BookingType.
const (
	Package12 BookingType = "package_12"
	Package4  BookingType = "package_4"
	Package8  BookingType = "package_8"
	Single    BookingType = "single"
	Trial     BookingType = "trial"
)

// Defines values for BusinessType.
const (
	ArtStudio       BusinessType = "art_studio"
	IndividualCoach BusinessType = "individual_coach"
	SwimmingSchool  BusinessType = "swimming_school"
	TutoringCenter  BusinessType = "tutoring_center"
)

// Defines values for ClassType.
const (
	ClassTypeLargeGroup ClassType = "large_group"
	ClassTypePrivate    ClassType = "private"
	ClassTypeSmallGroup ClassType = "small_group"
)

// Defines values for CoachStatus.
const (
	CoachStatusActive   CoachStatus = "active"
	CoachStatusInactive CoachStatus = "inactive"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusExpired  PaymentStatus = "expired"
	PaymentStatusFailed   PaymentStatus = "failed"
	PaymentStatusPending  PaymentStatus = "pending"
	PaymentStatusRefunded PaymentStatus = "refunded"
	PaymentStatusSuccess  PaymentStatus = "success"
)

// Defines values for PaymentStatusEnum.
const (
	Paid     PaymentStatusEnum = "paid"
	Refunded PaymentStatusEnum = "refunded"
	Unpaid   PaymentStatusEnum = "unpaid"
)

// Defines values for ServiceDetailCoachesStatus.
const (
	ServiceDetailCoachesStatusActive   ServiceDetailCoachesStatus = "active"
	ServiceDetailCoachesStatusInactive ServiceDetailCoachesStatus = "inactive"
)

// Defines values for ServiceStatus.
const (
	ServiceStatusActive   ServiceStatus = "active"
	ServiceStatusDraft    ServiceStatus = "draft"
	ServiceStatusInactive ServiceStatus = "inactive"
)

// Defines values for SessionStatus.
const (
	Cancelled SessionStatus = "cancelled"
	Completed SessionStatus = "completed"
	NoShow    SessionStatus = "no_show"
	Scheduled SessionStatus = "scheduled"
)

// Defines values for SkillLevel.
const (
	SkillLevelAdvanced     SkillLevel = "advanced"
	SkillLevelAllLevels    SkillLevel = "all_levels"
	SkillLevelBeginner     SkillLevel = "beginner"
	SkillLevelIntermediate SkillLevel = "intermediate"
)

// Defines values for UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleCoach  UserRole = "coach"
	UserRoleParent UserRole = "parent"
	UserRoleVendor UserRole = "vendor"
)

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusInactive  UserStatus = "inactive"
	UserStatusSuspended UserStatus = "suspended"
)

// Defines values for VendorStatus.
const (
	Active    VendorStatus = "active"
	Pending   VendorStatus = "pending"
	Rejected  VendorStatus = "rejected"
	Suspended VendorStatus = "suspended"
)

// Defines values for ClassTypeParam.
const (
	ClassTypeParamLargeGroup ClassTypeParam = "large_group"
	ClassTypeParamPrivate    ClassTypeParam = "private"
	ClassTypeParamSmallGroup ClassTypeParam = "small_group"
)

// Defines values for DayParam.
const (
	DayParamFriday    DayParam = "friday"
	DayParamMonday    DayParam = "monday"
	DayParamSaturday  DayParam = "saturday"
	DayParamSunday    DayParam = "sunday"
	DayParamThursday  DayParam = "thursday"
	DayParamTuesday   DayParam = "tuesday"
	DayParamWednesday DayParam = "wednesday"
)

// Defines values for PeriodParam.
const (
	PeriodParamDay   PeriodParam = "day"
	PeriodParamMonth PeriodParam = "month"
	PeriodParamWeek  PeriodParam = "week"
	PeriodParamYear  PeriodParam = "year"
)

// Defines values for SkillLevelParam.
const (
	SkillLevelParamAdvanced     SkillLevelParam = "advanced"
	SkillLevelParamAllLevels    SkillLevelParam = "all_levels"
	SkillLevelParamBeginner     SkillLevelParam = "beginner"
	SkillLevelParamIntermediate SkillLevelParam = "intermediate"
)

// Defines values for GetStatisticsParamsPeriod.
const (
	GetStatisticsParamsPeriodDay   GetStatisticsParamsPeriod = "day"
	GetStatisticsParamsPeriodMonth GetStatisticsParamsPeriod = "month"
	GetStatisticsParamsPeriodWeek  GetStatisticsParamsPeriod = "week"
	GetStatisticsParamsPeriodYear  GetStatisticsParamsPeriod = "year"
)

// Defines values for SearchServicesParamsSkillLevel.
const (
	Advanced     SearchServicesParamsSkillLevel = "advanced"
	AllLevels    SearchServicesParamsSkillLevel = "all_levels"
	Beginner     SearchServicesParamsSkillLevel = "beginner"
	Intermediate SearchServicesParamsSkillLevel = "intermediate"
)

// Defines values for SearchServicesParamsClassType.
const (
	LargeGroup SearchServicesParamsClassType = "large_group"
	Private    SearchServicesParamsClassType = "private"
	SmallGroup SearchServicesParamsClassType = "small_group"
)

// Defines values for SearchServicesParamsDay.
const (
	SearchServicesParamsDayFriday    SearchServicesParamsDay = "friday"
	SearchServicesParamsDayMonday    SearchServicesParamsDay = "monday"
	SearchServicesParamsDaySaturday  SearchServicesParamsDay = "saturday"
	SearchServicesParamsDaySunday    SearchServicesParamsDay = "sunday"
	SearchServicesParamsDayThursday  SearchServicesParamsDay = "thursday"
	SearchServicesParamsDayTuesday   SearchServicesParamsDay = "tuesday"
	SearchServicesParamsDayWednesday SearchServicesParamsDay = "wednesday"
)

// AvailableDate defines model for AvailableDate.
type AvailableDate struct {
	Date  *openapi_types.Date `json:"date,omitempty"`
	Slots *[]struct {
		AvailableSlots *int `json:"available_slots,omitempty"`
		Coach          *struct {
			Id   *int64  `json:"id,omitempty"`
			Name *string `json:"name,omitempty"`
		} `json:"coach,omitempty"`
		EndTime    *string `json:"end_time,omitempty"`
		ScheduleId *int64  `json:"schedule_id,omitempty"`
		StartTime  *string `json:"start_time,omitempty"`
	} `json:"slots,omitempty"`
}

// Booking defines model for Booking.
type Booking struct {
	BookingNumber *string      `json:"booking_number,omitempty"`
	BookingType   *BookingType `json:"booking_type,omitempty"`
	Child         *Child       `json:"child,omitempty"`
	Coach         *struct {
		FullName *string `json:"full_name,omitempty"`
		Id       *int64  `json:"id,omitempty"`
		Photo    *string `json:"photo,omitempty"`
	} `json:"coach,omitempty"`
	CompletedSessions *int       `json:"completed_sessions,omitempty"`
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	Id                *int64     `json:"id,omitempty"`
	NextSession       *struct {
		EndTime     *string             `json:"end_time,omitempty"`
		SessionDate *openapi_types.Date `json:"session_date,omitempty"`
		StartTime   *string             `json:"start_time,omitempty"`
	} `json:"next_session,omitempty"`
	PaymentStatus *PaymentStatusEnum `json:"payment_status,omitempty"`
	Service       *struct {
		Category *string `json:"category,omitempty"`
		Id       *int64  `json:"id,omitempty"`
		Name     *string `json:"name,omitempty"`
	} `json:"service,omitempty"`
	Status        *BookingStatus `json:"status,omitempty"`
	TotalAmount   *float64       `json:"total_amount,omitempty"`
	TotalSessions *int           `json:"total_sessions,omitempty"`
	Vendor        *struct {
		BusinessName *string `json:"business_name,omitempty"`
		Id           *int64  `json:"id,omitempty"`
		Logo         *string `json:"logo,omitempty"`
	} `json:"vendor,omitempty"`
}

// BookingDetail defines model for BookingDetail.
type BookingDetail struct {
	BookingNumber *string      `json:"booking_number,omitempty"`
	BookingType   *BookingType `json:"booking_type,omitempty"`
	Child         *Child       `json:"child,omitempty"`
	Coach         *struct {
		FullName *string `json:"full_name,omitempty"`
		Id       *int64  `json:"id,omitempty"`
		Photo    *string `json:"photo,omitempty"`
	} `json:"coach,omitempty"`
	CompletedSessions *int       `json:"completed_sessions,omitempty"`
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	Id                *int64     `json:"id,omitempty"`
	NextSession       *struct {
		EndTime     *string             `json:"end_time,omitempty"`
		SessionDate *openapi_types.Date `json:"session_date,omitempty"`
		StartTime   *string             `json:"start_time,omitempty"`
	} `json:"next_session,omitempty"`
	ParentNotes   *string            `json:"parent_notes,omitempty"`
	Payment       *Payment           `json:"payment,omitempty"`
	PaymentStatus *PaymentStatusEnum `json:"payment_status,omitempty"`
	Service       *struct {
		Category *string `json:"category,omitempty"`
		Id       *int64  `json:"id,omitempty"`
		Name     *string `json:"name,omitempty"`
	} `json:"service,omitempty"`
	Sessions      *[]BookingSession `json:"sessions,omitempty"`
	Status        *BookingStatus    `json:"status,omitempty"`
	TotalAmount   *float64          `json:"total_amount,omitempty"`
	TotalSessions *int              `json:"total_sessions,omitempty"`
	Vendor        *struct {
		BusinessName *string `json:"business_name,omitempty"`
		Id           *int64  `json:"id,omitempty"`
		Logo         *string `json:"logo,omitempty"`
	} `json:"vendor,omitempty"`
}

// BookingSession defines model for BookingSession.
type BookingSession struct {
	Attended      *bool               `json:"attended,omitempty"`
	CoachNotes    *string             `json:"coach_notes,omitempty"`
	CompletedAt   *time.Time          `json:"completed_at,omitempty"`
	EndTime       *string             `json:"end_time,omitempty"`
	Id            *int64              `json:"id,omitempty"`
	Rating        *int                `json:"rating,omitempty"`
	SessionDate   *openapi_types.Date `json:"session_date,omitempty"`
	SessionNumber *int                `json:"session_number,omitempty"`
	StartTime     *string             `json:"start_time,omitempty"`
	Status        *SessionStatus      `json:"status,omitempty"`
}

// BookingStatus defines model for BookingStatus.
type BookingStatus string

// BookingType defines model for BookingType.
type BookingType string

// BusinessType defines model for BusinessType.
type BusinessType string

// Category defines model for Category.
type Category struct {
	ColorHex     *string `json:"color_hex,omitempty"`
	Description  *string `json:"description,omitempty"`
	DisplayOrder *int    `json:"display_order,omitempty"`
	Icon         *string `json:"icon,omitempty"`
	Id           *int64  `json:"id,omitempty"`
	Name         *string `json:"name,omitempty"`
	Slug         *string `json:"slug,omitempty"`
}

// Child defines model for Child.
type Child struct {
	Age          *int                `json:"age,omitempty"`
	CreatedAt    *time.Time          `json:"created_at,omitempty"`
	DateOfBirth  *openapi_types.Date `json:"date_of_birth,omitempty"`
	Gender       *Gender             `json:"gender,omitempty"`
	Id           *int64              `json:"id,omitempty"`
	Name         *string             `json:"name,omitempty"`
	Nickname     *string             `json:"nickname,omitempty"`
	Photo        *string             `json:"photo,omitempty"`
	SpecialNeeds *string             `json:"special_needs,omitempty"`
}

// ClassType defines model for ClassType.
type ClassType string

// Coach defines model for Coach.
type Coach struct {
	Bio            *string `json:"bio,omitempty"`
	Certifications *[]struct {
		FileUrl *string `json:"file_url,omitempty"`
		Issuer  *string `json:"issuer,omitempty"`
		Name    *string `json:"name,omitempty"`
		Year    *int    `json:"year,omitempty"`
	} `json:"certifications,omitempty"`
	Education       *string      `json:"education,omitempty"`
	ExperienceYears *int         `json:"experience_years,omitempty"`
	FullName        *string      `json:"full_name,omitempty"`
	Id              *int64       `json:"id,omitempty"`
	IsFeatured      *bool        `json:"is_featured,omitempty"`
	Photo           *string      `json:"photo,omitempty"`
	Specializations *[]string    `json:"specializations,omitempty"`
	Status          *CoachStatus `json:"status,omitempty"`
}

// CoachStatus defines model for Coach.Status.
type CoachStatus string

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse struct {
	Error struct {
		Code    *string `json:"code,omitempty"`
		Details *[]struct {
			Field   *string `json:"field,omitempty"`
			Message *string `json:"message,omitempty"`
		} `json:"details,omitempty"`
		Message string `json:"message"`
	} `json:"error"`
}

// Gender defines model for Gender.
type Gender string

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      *int `json:"limit,omitempty"`
	Page       *int `json:"page,omitempty"`
	Total      *int `json:"total,omitempty"`
	TotalPages *int `json:"total_pages,omitempty"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount        *float64       `json:"amount,omitempty"`
	ExpiredAt     *time.Time     `json:"expired_at,omitempty"`
	PaidAt        *time.Time     `json:"paid_at,omitempty"`
	PaymentMethod *string        `json:"payment_method,omitempty"`
	PaymentNumber *string        `json:"payment_number,omitempty"`
	PaymentUrl    *string        `json:"payment_url,omitempty"`
	Status        *PaymentStatus `json:"status,omitempty"`
}

// PaymentStatus defines model for Payment.Status.
type PaymentStatus string

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod struct {
	Code           *string   `json:"code,omitempty"`
	Icon           *string   `json:"icon,omitempty"`
	Name           *string   `json:"name,omitempty"`
	Options        *[]string `json:"options,omitempty"`
	ProcessingTime *string   `json:"processing_time,omitempty"`
}

// PaymentStatusEnum defines model for PaymentStatusEnum.
type PaymentStatusEnum string

// Review defines model for Review.
type Review struct {
	ChildAge       *int       `json:"child_age,omitempty"`
	ChildEnjoyed   *bool      `json:"child_enjoyed,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	ParentName     *string    `json:"parent_name,omitempty"`
	Photos         *[]string  `json:"photos,omitempty"`
	Rating         *int       `json:"rating,omitempty"`
	RespondedAt    *time.Time `json:"responded_at,omitempty"`
	ReviewText     *string    `json:"review_text,omitempty"`
	VendorResponse *string    `json:"vendor_response,omitempty"`
	WouldRecommend *bool      `json:"would_recommend,omitempty"`
}

// ReviewSummary defines model for ReviewSummary.
type ReviewSummary struct {
	AverageRating          *float64 `json:"average_rating,omitempty"`
	ChildEnjoyedPercentage *float64 `json:"child_enjoyed_percentage,omitempty"`
	RatingDistribution     *struct {
		N1 *int `json:"1,omitempty"`
		N2 *int `json:"2,omitempty"`
		N3 *int `json:"3,omitempty"`
		N4 *int `json:"4,omitempty"`
		N5 *int `json:"5,omitempty"`
	} `json:"rating_distribution,omitempty"`
	TotalReviews             *int     `json:"total_reviews,omitempty"`
	WouldRecommendPercentage *float64 `json:"would_recommend_percentage,omitempty"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	AvailableSlots *int `json:"available_slots,omitempty"`
	Coach          *struct {
		Id   *int64  `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"coach,omitempty"`
	DayName   *string `json:"day_name,omitempty"`
	DayOfWeek *int    `json:"day_of_week,omitempty"`
	EndTime   *string `json:"end_time,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	StartTime *string `json:"start_time,omitempty"`
}

// Service defines model for Service.
type Service struct {
	AgeMax          *int           `json:"age_max,omitempty"`
	AgeMin          *int           `json:"age_min,omitempty"`
	AgeRange        *string        `json:"age_range,omitempty"`
	ClassType       *ClassType     `json:"class_type,omitempty"`
	Description     *string        `json:"description,omitempty"`
	DurationMinutes *int           `json:"duration_minutes,omitempty"`
	Id              *int64         `json:"id,omitempty"`
	IsFeatured      *bool          `json:"is_featured,omitempty"`
	MaxParticipants *int           `json:"max_participants,omitempty"`
	Name            *string        `json:"name,omitempty"`
	Package12Price  *float64       `json:"package_12_price,omitempty"`
	Package4Price   *float64       `json:"package_4_price,omitempty"`
	Package8Price   *float64       `json:"package_8_price,omitempty"`
	PricePerSession *float64       `json:"price_per_session,omitempty"`
	Requirements    *string        `json:"requirements,omitempty"`
	SkillLevel      *SkillLevel    `json:"skill_level,omitempty"`
	Status          *ServiceStatus `json:"status,omitempty"`
	TrialPrice      *float64       `json:"trial_price,omitempty"`
	WhatWillLearn   *string        `json:"what_will_learn,omitempty"`
}

// ServiceDetail defines model for ServiceDetail.
type ServiceDetail struct {
	AgeMax    *int       `json:"age_max,omitempty"`
	AgeMin    *int       `json:"age_min,omitempty"`
	AgeRange  *string    `json:"age_range,omitempty"`
	ClassType *ClassType `json:"class_type,omitempty"`
	Coaches   *[]struct {
		Bio            *string `json:"bio,omitempty"`
		Certifications *[]struct {
			FileUrl *string `json:"file_url,omitempty"`
			Issuer  *string `json:"issuer,omitempty"`
			Name    *string `json:"name,omitempty"`
			Year    *int    `json:"year,omitempty"`
		} `json:"certifications,omitempty"`
		Education       *string                     `json:"education,omitempty"`
		ExperienceYears *int                        `json:"experience_years,omitempty"`
		FullName        *string                     `json:"full_name,omitempty"`
		Id              *int64                      `json:"id,omitempty"`
		IsFeatured      *bool                       `json:"is_featured,omitempty"`
		IsPrimary       *bool                       `json:"is_primary,omitempty"`
		Photo           *string                     `json:"photo,omitempty"`
		Specializations *[]string                   `json:"specializations,omitempty"`
		Status          *ServiceDetailCoachesStatus `json:"status,omitempty"`
	} `json:"coaches,omitempty"`
	Description     *string  `json:"description,omitempty"`
	DurationMinutes *int     `json:"duration_minutes,omitempty"`
	Id              *int64   `json:"id,omitempty"`
	IsFeatured      *bool    `json:"is_featured,omitempty"`
	MaxParticipants *int     `json:"max_participants,omitempty"`
	Name            *string  `json:"name,omitempty"`
	Package12Price  *float64 `json:"package_12_price,omitempty"`
	Package4Price   *float64 `json:"package_4_price,omitempty"`
	Package8Price   *float64 `json:"package_8_price,omitempty"`
	PricePerSession *float64 `json:"price_per_session,omitempty"`
	Pricing         *struct {
		Package12 *float64 `json:"package_12,omitempty"`
		Package4  *float64 `json:"package_4,omitempty"`
		Package8  *float64 `json:"package_8,omitempty"`
		Single    *float64 `json:"single,omitempty"`
		Trial     *float64 `json:"trial,omitempty"`
	} `json:"pricing,omitempty"`
	Requirements   *string        `json:"requirements,omitempty"`
	ReviewsPreview *[]Review      `json:"reviews_preview,omitempty"`
	Schedules      *[]Schedule    `json:"schedules,omitempty"`
	SkillLevel     *SkillLevel    `json:"skill_level,omitempty"`
	Status         *ServiceStatus `json:"status,omitempty"`
	TrialPrice     *float64       `json:"trial_price,omitempty"`
	Vendor         *Vendor        `json:"vendor,omitempty"`
	WhatWillLearn  *string        `json:"what_will_learn,omitempty"`
}

// ServiceDetailCoachesStatus defines model for ServiceDetail.Coaches.Status.
type ServiceDetailCoachesStatus string

// ServiceStatus defines model for ServiceStatus.
type ServiceStatus string

// ServiceWithVendor defines model for ServiceWithVendor.
type ServiceWithVendor struct {
	AgeMax          *int                `json:"age_max,omitempty"`
	AgeMin          *int                `json:"age_min,omitempty"`
	AgeRange        *string             `json:"age_range,omitempty"`
	AvailableDays   *[]string           `json:"available_days,omitempty"`
	Category        *Category           `json:"category,omitempty"`
	ClassType       *ClassType          `json:"class_type,omitempty"`
	Description     *string             `json:"description,omitempty"`
	DistanceKm      *float64            `json:"distance_km,omitempty"`
	DurationMinutes *int                `json:"duration_minutes,omitempty"`
	Id              *int64              `json:"id,omitempty"`
	IsFeatured      *bool               `json:"is_featured,omitempty"`
	MaxParticipants *int                `json:"max_participants,omitempty"`
	Name            *string             `json:"name,omitempty"`
	NextAvailable   *openapi_types.Date `json:"next_available,omitempty"`
	Package12Price  *float64            `json:"package_12_price,omitempty"`
	Package4Price   *float64            `json:"package_4_price,omitempty"`
	Package8Price   *float64            `json:"package_8_price,omitempty"`
	PricePerSession *float64            `json:"price_per_session,omitempty"`
	Requirements    *string             `json:"requirements,omitempty"`
	SkillLevel      *SkillLevel         `json:"skill_level,omitempty"`
	Status          *ServiceStatus      `json:"status,omitempty"`
	TrialPrice      *float64            `json:"trial_price,omitempty"`
	Vendor          *Vendor             `json:"vendor,omitempty"`
	WhatWillLearn   *string             `json:"what_will_learn,omitempty"`
}

// SessionStatus defines model for SessionStatus.
type SessionStatus string

// SkillLevel defines model for SkillLevel.
type SkillLevel string

// Statistics defines model for Statistics.
type Statistics struct {
	ActiveBookings   *int     `json:"active_bookings,omitempty"`
	CommissionEarned *float64 `json:"commission_earned,omitempty"`
	Growth           *struct {
		Bookings *string `json:"bookings,omitempty"`
		Revenue  *string `json:"revenue,omitempty"`
		Users    *string `json:"users,omitempty"`
	} `json:"growth,omitempty"`
	PopularCategories *[]struct {
		Name          *string  `json:"name,omitempty"`
		Percentage    *float64 `json:"percentage,omitempty"`
		TotalBookings *int     `json:"total_bookings,omitempty"`
	} `json:"popular_categories,omitempty"`
	TotalBookings *int     `json:"total_bookings,omitempty"`
	TotalCoaches  *int     `json:"total_coaches,omitempty"`
	TotalParents  *int     `json:"total_parents,omitempty"`
	TotalRevenue  *float64 `json:"total_revenue,omitempty"`
	TotalUsers    *int     `json:"total_users,omitempty"`
	TotalVendors  *int     `json:"total_vendors,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time  `json:"created_at,omitempty"`
	Email     *string     `json:"email,omitempty"`
	FullName  *string     `json:"full_name,omitempty"`
	Id        *int64      `json:"id,omitempty"`
	Phone     *string     `json:"phone,omitempty"`
	Role      *UserRole   `json:"role,omitempty"`
	Status    *UserStatus `json:"status,omitempty"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserStatus defines model for UserStatus.
type UserStatus string

// Vendor defines model for Vendor.
type Vendor struct {
	Address       *string       `json:"address,omitempty"`
	Amenities     *[]string     `json:"amenities,omitempty"`
	BusinessName  *string       `json:"business_name,omitempty"`
	BusinessType  *BusinessType `json:"business_type,omitempty"`
	City          *string       `json:"city,omitempty"`
	CoverImage    *string       `json:"cover_image,omitempty"`
	Description   *string       `json:"description,omitempty"`
	District      *string       `json:"district,omitempty"`
	Id            *int64        `json:"id,omitempty"`
	Latitude      *float64      `json:"latitude,omitempty"`
	Logo          *string       `json:"logo,omitempty"`
	Longitude     *float64      `json:"longitude,omitempty"`
	Phone         *string       `json:"phone,omitempty"`
	Photos        *[]string     `json:"photos,omitempty"`
	RatingAvg     *float64      `json:"rating_avg,omitempty"`
	Status        *VendorStatus `json:"status,omitempty"`
	TotalBookings *int          `json:"total_bookings,omitempty"`
	TotalReviews  *int          `json:"total_reviews,omitempty"`
	Verified      *bool         `json:"verified,omitempty"`
	Whatsapp      *string       `json:"whatsapp,omitempty"`
}

// VendorBooking defines model for VendorBooking.
type VendorBooking struct {
	BookingNumber *string `json:"booking_number,omitempty"`
	Child         *struct {
		Age   *int    `json:"age,omitempty"`
		Name  *string `json:"name,omitempty"`
		Photo *string `json:"photo,omitempty"`
	} `json:"child,omitempty"`
	Coach *struct {
		FullName *string `json:"full_name,omitempty"`
	} `json:"coach,omitempty"`
	Id     *int64 `json:"id,omitempty"`
	Parent *struct {
		FullName *string `json:"full_name,omitempty"`
		Phone    *string `json:"phone,omitempty"`
		Whatsapp *string `json:"whatsapp,omitempty"`
	} `json:"parent,omitempty"`
	ParentNotes *string `json:"parent_notes,omitempty"`
	Service     *struct {
		Name *string `json:"name,omitempty"`
	} `json:"service,omitempty"`
	Session *struct {
		EndTime       *string             `json:"end_time,omitempty"`
		SessionDate   *openapi_types.Date `json:"session_date,omitempty"`
		SessionNumber *int                `json:"session_number,omitempty"`
		StartTime     *string             `json:"start_time,omitempty"`
		Status        *SessionStatus      `json:"status,omitempty"`
	} `json:"session,omitempty"`
}

// VendorDashboard defines model for VendorDashboard.
type VendorDashboard struct {
	Overview *struct {
		ActiveCoaches   *int     `json:"active_coaches,omitempty"`
		PendingBookings *int     `json:"pending_bookings,omitempty"`
		RatingAvg       *float64 `json:"rating_avg,omitempty"`
		TotalReviews    *int     `json:"total_reviews,omitempty"`
		TotalServices   *int     `json:"total_services,omitempty"`
	} `json:"overview,omitempty"`
	ThisMonth *struct {
		NewCustomers  *int     `json:"new_customers,omitempty"`
		Revenue       *float64 `json:"revenue,omitempty"`
		TotalBookings *int     `json:"total_bookings,omitempty"`
	} `json:"this_month,omitempty"`
	ThisWeek *struct {
		NewCustomers  *int     `json:"new_customers,omitempty"`
		Revenue       *float64 `json:"revenue,omitempty"`
		TotalBookings *int     `json:"total_bookings,omitempty"`
	} `json:"this_week,omitempty"`
	Today *struct {
		CompletedSessions *int     `json:"completed_sessions,omitempty"`
		Revenue           *float64 `json:"revenue,omitempty"`
		TotalSessions     *int     `json:"total_sessions,omitempty"`
		UpcomingSessions  *int     `json:"upcoming_sessions,omitempty"`
	} `json:"today,omitempty"`
}

// VendorStatus defines model for VendorStatus.
type VendorStatus string

// AgeParam defines model for AgeParam.
type AgeParam = int

// BookingStatusParam defines model for BookingStatusParam.
type BookingStatusParam = BookingStatus

// CategoryParam defines model for CategoryParam.
type CategoryParam = string

// ChildIdParam defines model for ChildIdParam.
type ChildIdParam = int64

// CityParam defines model for CityParam.
type CityParam = string

// ClassTypeParam defines model for ClassTypeParam.
type ClassTypeParam string

// CoachIdParam defines model for CoachIdParam.
type CoachIdParam = int64

// DateParam defines model for DateParam.
type DateParam = openapi_types.Date

// DayParam defines model for DayParam.
type DayParam string

// DistrictParam defines model for DistrictParam.
type DistrictParam = string

// IdParam defines model for IdParam.
type IdParam = int64

// IsFeaturedParam defines model for IsFeaturedParam.
type IsFeaturedParam = bool

// LimitParam defines model for LimitParam.
type LimitParam = int

// MonthParam defines model for MonthParam.
type MonthParam = string

// PageParam defines model for PageParam.
type PageParam = int

// PaymentNumberParam defines model for PaymentNumberParam.
type PaymentNumberParam = string

// PeriodParam defines model for PeriodParam.
type PeriodParam string

// PriceMaxParam defines model for PriceMaxParam.
type PriceMaxParam = float64

// PriceMinParam defines model for PriceMinParam.
type PriceMinParam = float64

// RatingMinParam defines model for RatingMinParam.
type RatingMinParam = float64

// ReviewIdParam defines model for ReviewIdParam.
type ReviewIdParam = int64

// ServiceIdParam defines model for ServiceIdParam.
type ServiceIdParam = int64

// SessionIdParam defines model for SessionIdParam.
type SessionIdParam = int64

// SkillLevelParam defines model for SkillLevelParam.
type SkillLevelParam string

// UpcomingParam defines model for UpcomingParam.
type UpcomingParam = bool

// VendorStatusParam defines model for VendorStatusParam.
type VendorStatusParam = VendorStatus

// AdminVendorsResponse defines model for AdminVendorsResponse.
type AdminVendorsResponse struct {
	Data struct {
		Pagination *Pagination `json:"pagination,omitempty"`
		Vendors    *[]struct {
			Address       *string       `json:"address,omitempty"`
			Amenities     *[]string     `json:"amenities,omitempty"`
			BusinessName  *string       `json:"business_name,omitempty"`
			BusinessType  *BusinessType `json:"business_type,omitempty"`
			City          *string       `json:"city,omitempty"`
			CoverImage    *string       `json:"cover_image,omitempty"`
			CreatedAt     *time.Time    `json:"created_at,omitempty"`
			Description   *string       `json:"description,omitempty"`
			District      *string       `json:"district,omitempty"`
			Id            *int64        `json:"id,omitempty"`
			Latitude      *float64      `json:"latitude,omitempty"`
			Logo          *string       `json:"logo,omitempty"`
			Longitude     *float64      `json:"longitude,omitempty"`
			Phone         *string       `json:"phone,omitempty"`
			Photos        *[]string     `json:"photos,omitempty"`
			RatingAvg     *float64      `json:"rating_avg,omitempty"`
			Status        *VendorStatus `json:"status,omitempty"`
			TotalBookings *int          `json:"total_bookings,omitempty"`
			TotalReviews  *int          `json:"total_reviews,omitempty"`
			User          *struct {
				Email    *string `json:"email,omitempty"`
				FullName *string `json:"full_name,omitempty"`
				Phone    *string `json:"phone,omitempty"`
			} `json:"user,omitempty"`
			Verified *bool   `json:"verified,omitempty"`
			Whatsapp *string `json:"whatsapp,omitempty"`
		} `json:"vendors,omitempty"`
	} `json:"data"`
}

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse = DefaultErrorResponse

// BookingCancelledResponse defines model for BookingCancelledResponse.
type BookingCancelledResponse struct {
	Data struct {
		Booking *struct {
			RefundAmount *float64       `json:"refund_amount,omitempty"`
			RefundStatus *string        `json:"refund_status,omitempty"`
			Status       *BookingStatus `json:"status,omitempty"`
		} `json:"booking,omitempty"`
	} `json:"data"`
	Message *string `json:"message,omitempty"`
}

// BookingCreatedResponse defines model for BookingCreatedResponse.
type BookingCreatedResponse struct {
	Data struct {
		Booking *BookingDetail `json:"booking,omitempty"`
	} `json:"data"`
	Message *string `json:"message,omitempty"`
}

// BookingDetailResponse defines model for BookingDetailResponse.
type BookingDetailResponse struct {
	Data BookingDetail `json:"data"`
}

// BookingsListResponse defines model for BookingsListResponse.
type BookingsListResponse struct {
	Data []Booking `json:"data"`
}

// CategoriesResponse defines model for CategoriesResponse.
type CategoriesResponse struct {
	Data []Category `json:"data"`
}

// ChildResponse defines model for ChildResponse.
type ChildResponse struct {
	Data Child `json:"data"`
}

// ChildrenListResponse defines model for ChildrenListResponse.
type ChildrenListResponse struct {
	Data []Child `json:"data"`
}

// CoachCreatedResponse defines model for CoachCreatedResponse.
type CoachCreatedResponse struct {
	Data struct {
		Coach *Coach `json:"coach,omitempty"`
	} `json:"data"`
}

// ConflictResponse defines model for ConflictResponse.
type ConflictResponse = DefaultErrorResponse

// ForbiddenResponse defines model for ForbiddenResponse.
type ForbiddenResponse = DefaultErrorResponse

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse = DefaultErrorResponse

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Data struct {
		Token string `json:"token"`
		User  User   `json:"user"`
	} `json:"data"`
}

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse = DefaultErrorResponse

// PaymentMethodsResponse defines model for PaymentMethodsResponse.
type PaymentMethodsResponse struct {
	Data []PaymentMethod `json:"data"`
}

// PaymentStatusResponse defines model for PaymentStatusResponse.
type PaymentStatusResponse struct {
	Data struct {
		Amount  *float64 `json:"amount,omitempty"`
		Booking *struct {
			BookingNumber *string        `json:"booking_number,omitempty"`
			Status        *BookingStatus `json:"status,omitempty"`
		} `json:"booking,omitempty"`
		PaidAt        *time.Time `json:"paid_at,omitempty"`
		PaymentMethod *string    `json:"payment_method,omitempty"`
		PaymentNumber *string    `json:"payment_number,omitempty"`
		Status        *string    `json:"status,omitempty"`
	} `json:"data"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	Data struct {
		Token string `json:"token"`
		User  User   `json:"user"`
	} `json:"data"`
	Message *string `json:"message,omitempty"`
}

// RegisterVendorResponse defines model for RegisterVendorResponse.
type RegisterVendorResponse struct {
	Data struct {
		User   User   `json:"user"`
		Vendor Vendor `json:"vendor"`
	} `json:"data"`
	Message *string `json:"message,omitempty"`
}

// ReviewCreatedResponse defines model for ReviewCreatedResponse.
type ReviewCreatedResponse struct {
	Data struct {
		Review *Review `json:"review,omitempty"`
	} `json:"data"`
	Message *string `json:"message,omitempty"`
}

// ScheduleCreatedResponse defines model for ScheduleCreatedResponse.
type ScheduleCreatedResponse struct {
	Data struct {
		Schedule *Schedule `json:"schedule,omitempty"`
	} `json:"data"`
}

// ScheduleExceptionCreatedResponse defines model for ScheduleExceptionCreatedResponse.
type ScheduleExceptionCreatedResponse struct {
	Data struct {
		Message *string `json:"message,omitempty"`
	} `json:"data"`
}

// ServiceAvailabilityResponse defines model for ServiceAvailabilityResponse.
type ServiceAvailabilityResponse struct {
	Data struct {
		AvailableDates *[]AvailableDate `json:"available_dates,omitempty"`
		Exceptions     *[]struct {
			Date   *openapi_types.Date `json:"date,omitempty"`
			Reason *string             `json:"reason,omitempty"`
		} `json:"exceptions,omitempty"`
	} `json:"data"`
}

// ServiceCreatedResponse defines model for ServiceCreatedResponse.
type ServiceCreatedResponse struct {
	Data struct {
		Service *Service `json:"service,omitempty"`
	} `json:"data"`
}

// ServiceDetailResponse defines model for ServiceDetailResponse.
type ServiceDetailResponse struct {
	Data ServiceDetail `json:"data"`
}

// ServiceReviewsResponse defines model for ServiceReviewsResponse.
type ServiceReviewsResponse struct {
	Data struct {
		Pagination *Pagination    `json:"pagination,omitempty"`
		Reviews    *[]Review      `json:"reviews,omitempty"`
		Summary    *ReviewSummary `json:"summary,omitempty"`
	} `json:"data"`
}

// ServiceUpdatedResponse defines model for ServiceUpdatedResponse.
type ServiceUpdatedResponse struct {
	Data struct {
		Service *Service `json:"service,omitempty"`
	} `json:"data"`
}

// ServicesSearchResponse defines model for ServicesSearchResponse.
type ServicesSearchResponse struct {
	Data struct {
		Pagination *Pagination          `json:"pagination,omitempty"`
		Services   *[]ServiceWithVendor `json:"services,omitempty"`
	} `json:"data"`
}

// SessionCompletedResponse defines model for SessionCompletedResponse.
type SessionCompletedResponse struct {
	Data struct {
		Session *BookingSession `json:"session,omitempty"`
	} `json:"data"`
	Message *string `json:"message,omitempty"`
}

// StatisticsResponse defines model for StatisticsResponse.
type StatisticsResponse struct {
	Data Statistics `json:"data"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse = map[string]interface{}

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse = DefaultErrorResponse

// VendorBookingsResponse defines model for VendorBookingsResponse.
type VendorBookingsResponse struct {
	Data []VendorBooking `json:"data"`
}

// VendorCoachesResponse defines model for VendorCoachesResponse.
type VendorCoachesResponse struct {
	Data []Coach `json:"data"`
}

// VendorDashboardResponse defines model for VendorDashboardResponse.
type VendorDashboardResponse struct {
	Data VendorDashboard `json:"data"`
}

// VendorServicesResponse defines model for VendorServicesResponse.
type VendorServicesResponse struct {
	Data struct {
		Pagination *Pagination `json:"pagination,omitempty"`
		Services   *[]Service  `json:"services,omitempty"`
	} `json:"data"`
}

// AddChildRequest defines model for AddChildRequest.
type AddChildRequest struct {
	DateOfBirth  openapi_types.Date `json:"date_of_birth"`
	Gender       Gender             `json:"gender"`
	Name         string             `json:"name"`
	Nickname     *string            `json:"nickname,omitempty"`
	SpecialNeeds *string            `json:"special_needs,omitempty"`
}

// AddCoachRequest defines model for AddCoachRequest.
type AddCoachRequest struct {
	Bio            *string `json:"bio,omitempty"`
	Certifications *[]struct {
		Issuer *string `json:"issuer,omitempty"`
		Name   *string `json:"name,omitempty"`
		Year   *int    `json:"year,omitempty"`
	} `json:"certifications,omitempty"`
	Education       *string   `json:"education,omitempty"`
	Email           string    `json:"email"`
	ExperienceYears *int      `json:"experience_years,omitempty"`
	FullName        string    `json:"full_name"`
	Phone           string    `json:"phone"`
	Specializations *[]string `json:"specializations,omitempty"`
}

// AddScheduleExceptionRequest defines model for AddScheduleExceptionRequest.
type AddScheduleExceptionRequest struct {
	ExceptionDate openapi_types.Date `json:"exception_date"`
	Reason        string             `json:"reason"`
}

// AddScheduleRequest defines model for AddScheduleRequest.
type AddScheduleRequest struct {
	AvailableSlots int    `json:"available_slots"`
	CoachId        *int64 `json:"coach_id,omitempty"`
	DayOfWeek      int    `json:"day_of_week"`
	EndTime        string `json:"end_time"`
	StartTime      string `json:"start_time"`
}

// AssignCoachRequest defines model for AssignCoachRequest.
type AssignCoachRequest struct {
	CoachId   int64 `json:"coach_id"`
	IsPrimary *bool `json:"is_primary,omitempty"`
}

// CancelBookingRequest defines model for CancelBookingRequest.
type CancelBookingRequest struct {
	CancellationReason string `json:"cancellation_reason"`
}

// CompleteSessionRequest defines model for CompleteSessionRequest.
type CompleteSessionRequest struct {
	Attended   bool    `json:"attended"`
	CoachNotes *string `json:"coach_notes,omitempty"`
}

// CreateBookingRequest defines model for CreateBookingRequest.
type CreateBookingRequest struct {
	BookingType BookingType `json:"booking_type"`
	ChildId     int64       `json:"child_id"`
	CoachId     *int64      `json:"coach_id,omitempty"`
	ParentNotes *string     `json:"parent_notes,omitempty"`
	ServiceId   int64       `json:"service_id"`
	Sessions    []struct {
		EndTime     *string            `json:"end_time,omitempty"`
		ScheduleId  *int64             `json:"schedule_id,omitempty"`
		SessionDate openapi_types.Date `json:"session_date"`
		StartTime   string             `json:"start_time"`
	} `json:"sessions"`
}

// CreateReviewRequest defines model for CreateReviewRequest.
type CreateReviewRequest struct {
	BookingId      int64   `json:"booking_id"`
	ChildEnjoyed   *bool   `json:"child_enjoyed,omitempty"`
	Rating         int     `json:"rating"`
	ReviewText     *string `json:"review_text,omitempty"`
	WouldRecommend *bool   `json:"would_recommend,omitempty"`
}

// CreateServiceRequest defines model for CreateServiceRequest.
type CreateServiceRequest struct {
	AgeMax          *int        `json:"age_max,omitempty"`
	AgeMin          *int        `json:"age_min,omitempty"`
	CategoryId      int64       `json:"category_id"`
	ClassType       ClassType   `json:"class_type"`
	Description     string      `json:"description"`
	DurationMinutes int         `json:"duration_minutes"`
	MaxParticipants *int        `json:"max_participants,omitempty"`
	Name            string      `json:"name"`
	Package12Price  *float64    `json:"package_12_price,omitempty"`
	Package4Price   *float64    `json:"package_4_price,omitempty"`
	Package8Price   *float64    `json:"package_8_price,omitempty"`
	PricePerSession float64     `json:"price_per_session"`
	Requirements    *string     `json:"requirements,omitempty"`
	SkillLevel      *SkillLevel `json:"skill_level,omitempty"`
	TrialPrice      *float64    `json:"trial_price,omitempty"`
	WhatWillLearn   *string     `json:"what_will_learn,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PaymentCallbackRequest defines model for PaymentCallbackRequest.
type PaymentCallbackRequest struct {
	GrossAmount       *string `json:"gross_amount,omitempty"`
	OrderId           *string `json:"order_id,omitempty"`
	StatusCode        *string `json:"status_code,omitempty"`
	TransactionStatus *string `json:"transaction_status,omitempty"`
}

// RegisterParentRequest defines model for RegisterParentRequest.
type RegisterParentRequest struct {
	City     *string `json:"city,omitempty"`
	District *string `json:"district,omitempty"`
	Email    string  `json:"email"`
	FullName string  `json:"full_name"`
	Password string  `json:"password"`
	Phone    string  `json:"phone"`
}

// RegisterVendorRequest defines model for RegisterVendorRequest.
type RegisterVendorRequest struct {
	Address      string       `json:"address"`
	BusinessName string       `json:"business_name"`
	BusinessType BusinessType `json:"business_type"`
	City         string       `json:"city"`
	District     *string      `json:"district,omitempty"`
	Email        string       `json:"email"`
	FullName     string       `json:"full_name"`
	Password     string       `json:"password"`
	Phone        string       `json:"phone"`
	Whatsapp     *string      `json:"whatsapp,omitempty"`
}

// RejectVendorRequest defines model for RejectVendorRequest.
type RejectVendorRequest struct {
	Reason string `json:"reason"`
}

// RespondToReviewRequest defines model for RespondToReviewRequest.
type RespondToReviewRequest struct {
	Response string `json:"response"`
}

// UpdateChildRequest defines model for UpdateChildRequest.
type UpdateChildRequest struct {
	Name         *string `json:"name,omitempty"`
	Nickname     *string `json:"nickname,omitempty"`
	SpecialNeeds *string `json:"special_needs,omitempty"`
}

// UpdateServiceRequest defines model for UpdateServiceRequest.
type UpdateServiceRequest struct {
	Description     *string        `json:"description,omitempty"`
	Name            *string        `json:"name,omitempty"`
	PricePerSession *float64       `json:"price_per_session,omitempty"`
	Status          *ServiceStatus `json:"status,omitempty"`
	TrialPrice      *float64       `json:"trial_price,omitempty"`
}

// GetStatisticsParams defines parameters for GetStatistics.
type GetStatisticsParams struct {
	Period *GetStatisticsParamsPeriod `form:"period,omitempty" json:"period,omitempty"`
}

// GetStatisticsParamsPeriod defines parameters for GetStatistics.
type GetStatisticsParamsPeriod string

// GetVendorsParams defines parameters for GetVendors.
type GetVendorsParams struct {
	Status *VendorStatusParam `form:"status,omitempty" json:"status,omitempty"`
	Page   *PageParam         `form:"page,omitempty" json:"page,omitempty"`
	Limit  *LimitParam        `form:"limit,omitempty" json:"limit,omitempty"`
}

// RejectVendorJSONBody defines parameters for RejectVendor.
type RejectVendorJSONBody struct {
	Reason string `json:"reason"`
}

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterParentJSONBody defines parameters for RegisterParent.
type RegisterParentJSONBody struct {
	City     *string `json:"city,omitempty"`
	District *string `json:"district,omitempty"`
	Email    string  `json:"email"`
	FullName string  `json:"full_name"`
	Password string  `json:"password"`
	Phone    string  `json:"phone"`
}

// RegisterVendorJSONBody defines parameters for RegisterVendor.
type RegisterVendorJSONBody struct {
	Address      string       `json:"address"`
	BusinessName string       `json:"business_name"`
	BusinessType BusinessType `json:"business_type"`
	City         string       `json:"city"`
	District     *string      `json:"district,omitempty"`
	Email        string       `json:"email"`
	FullName     string       `json:"full_name"`
	Password     string       `json:"password"`
	Phone        string       `json:"phone"`
	Whatsapp     *string      `json:"whatsapp,omitempty"`
}

// GetBookingsParams defines parameters for GetBookings.
type GetBookingsParams struct {
	Status   *BookingStatusParam `form:"status,omitempty" json:"status,omitempty"`
	ChildId  *ChildIdParam       `form:"child_id,omitempty" json:"child_id,omitempty"`
	Upcoming *UpcomingParam      `form:"upcoming,omitempty" json:"upcoming,omitempty"`
	Page     *PageParam          `form:"page,omitempty" json:"page,omitempty"`
	Limit    *LimitParam         `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateBookingJSONBody defines parameters for CreateBooking.
type CreateBookingJSONBody struct {
	BookingType BookingType `json:"booking_type"`
	ChildId     int64       `json:"child_id"`
	CoachId     *int64      `json:"coach_id,omitempty"`
	ParentNotes *string     `json:"parent_notes,omitempty"`
	ServiceId   int64       `json:"service_id"`
	Sessions    []struct {
		EndTime     *string            `json:"end_time,omitempty"`
		ScheduleId  *int64             `json:"schedule_id,omitempty"`
		SessionDate openapi_types.Date `json:"session_date"`
		StartTime   string             `json:"start_time"`
	} `json:"sessions"`
}

// CancelBookingJSONBody defines parameters for CancelBooking.
type CancelBookingJSONBody struct {
	CancellationReason string `json:"cancellation_reason"`
}

// AddChildJSONBody defines parameters for AddChild.
type AddChildJSONBody struct {
	DateOfBirth  openapi_types.Date `json:"date_of_birth"`
	Gender       Gender             `json:"gender"`
	Name         string             `json:"name"`
	Nickname     *string            `json:"nickname,omitempty"`
	SpecialNeeds *string            `json:"special_needs,omitempty"`
}

// UpdateChildJSONBody defines parameters for UpdateChild.
type UpdateChildJSONBody struct {
	Name         *string `json:"name,omitempty"`
	Nickname     *string `json:"nickname,omitempty"`
	SpecialNeeds *string `json:"special_needs,omitempty"`
}

// PaymentCallbackJSONBody defines parameters for PaymentCallback.
type PaymentCallbackJSONBody struct {
	GrossAmount       *string `json:"gross_amount,omitempty"`
	OrderId           *string `json:"order_id,omitempty"`
	StatusCode        *string `json:"status_code,omitempty"`
	TransactionStatus *string `json:"transaction_status,omitempty"`
}

// CreateReviewJSONBody defines parameters for CreateReview.
type CreateReviewJSONBody struct {
	BookingId      int64   `json:"booking_id"`
	ChildEnjoyed   *bool   `json:"child_enjoyed,omitempty"`
	Rating         int     `json:"rating"`
	ReviewText     *string `json:"review_text,omitempty"`
	WouldRecommend *bool   `json:"would_recommend,omitempty"`
}

// SearchServicesParams defines parameters for SearchServices.
type SearchServicesParams struct {
	// Category Category slug (swimming, math-tutoring, art-drawing)
	Category *CategoryParam `form:"category,omitempty" json:"category,omitempty"`
	City     *CityParam     `form:"city,omitempty" json:"city,omitempty"`
	District *DistrictParam `form:"district,omitempty" json:"district,omitempty"`

	// Age Child age in years
	Age        *AgeParam                       `form:"age,omitempty" json:"age,omitempty"`
	SkillLevel *SearchServicesParamsSkillLevel `form:"skill_level,omitempty" json:"skill_level,omitempty"`
	ClassType  *SearchServicesParamsClassType  `form:"class_type,omitempty" json:"class_type,omitempty"`
	Day        *SearchServicesParamsDay        `form:"day,omitempty" json:"day,omitempty"`
	PriceMin   *PriceMinParam                  `form:"price_min,omitempty" json:"price_min,omitempty"`
	PriceMax   *PriceMaxParam                  `form:"price_max,omitempty" json:"price_max,omitempty"`
	RatingMin  *RatingMinParam                 `form:"rating_min,omitempty" json:"rating_min,omitempty"`
	IsFeatured *IsFeaturedParam                `form:"is_featured,omitempty" json:"is_featured,omitempty"`
	Page       *PageParam                      `form:"page,omitempty" json:"page,omitempty"`
	Limit      *LimitParam                     `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchServicesParamsSkillLevel defines parameters for SearchServices.
type SearchServicesParamsSkillLevel string

// SearchServicesParamsClassType defines parameters for SearchServices.
type SearchServicesParamsClassType string

// SearchServicesParamsDay defines parameters for SearchServices.
type SearchServicesParamsDay string

// GetServiceAvailabilityParams defines parameters for GetServiceAvailability.
type GetServiceAvailabilityParams struct {
	// Month Month in YYYY-MM format
	Month MonthParam `form:"month" json:"month"`
}

// GetServiceReviewsParams defines parameters for GetServiceReviews.
type GetServiceReviewsParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetVendorBookingsParams defines parameters for GetVendorBookings.
type GetVendorBookingsParams struct {
	Date   *DateParam          `form:"date,omitempty" json:"date,omitempty"`
	Status *BookingStatusParam `form:"status,omitempty" json:"status,omitempty"`
	Page   *PageParam          `form:"page,omitempty" json:"page,omitempty"`
	Limit  *LimitParam         `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddCoachJSONBody defines parameters for AddCoach.
type AddCoachJSONBody struct {
	Bio            *string `json:"bio,omitempty"`
	Certifications *[]struct {
		Issuer *string `json:"issuer,omitempty"`
		Name   *string `json:"name,omitempty"`
		Year   *int    `json:"year,omitempty"`
	} `json:"certifications,omitempty"`
	Education       *string   `json:"education,omitempty"`
	Email           string    `json:"email"`
	ExperienceYears *int      `json:"experience_years,omitempty"`
	FullName        string    `json:"full_name"`
	Phone           string    `json:"phone"`
	Specializations *[]string `json:"specializations,omitempty"`
}

// RespondToReviewJSONBody defines parameters for RespondToReview.
type RespondToReviewJSONBody struct {
	Response string `json:"response"`
}

// AddScheduleExceptionJSONBody defines parameters for AddScheduleException.
type AddScheduleExceptionJSONBody struct {
	ExceptionDate openapi_types.Date `json:"exception_date"`
	Reason        string             `json:"reason"`
}

// GetVendorServicesParams defines parameters for GetVendorServices.
type GetVendorServicesParams struct {
	Page  *PageParam  `form:"page,omitempty" json:"page,omitempty"`
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateServiceJSONBody defines parameters for CreateService.
type CreateServiceJSONBody struct {
	AgeMax          *int        `json:"age_max,omitempty"`
	AgeMin          *int        `json:"age_min,omitempty"`
	CategoryId      int64       `json:"category_id"`
	ClassType       ClassType   `json:"class_type"`
	Description     string      `json:"description"`
	DurationMinutes int         `json:"duration_minutes"`
	MaxParticipants *int        `json:"max_participants,omitempty"`
	Name            string      `json:"name"`
	Package12Price  *float64    `json:"package_12_price,omitempty"`
	Package4Price   *float64    `json:"package_4_price,omitempty"`
	Package8Price   *float64    `json:"package_8_price,omitempty"`
	PricePerSession float64     `json:"price_per_session"`
	Requirements    *string     `json:"requirements,omitempty"`
	SkillLevel      *SkillLevel `json:"skill_level,omitempty"`
	TrialPrice      *float64    `json:"trial_price,omitempty"`
	WhatWillLearn   *string     `json:"what_will_learn,omitempty"`
}

// UpdateServiceJSONBody defines parameters for UpdateService.
type UpdateServiceJSONBody struct {
	Description     *string        `json:"description,omitempty"`
	Name            *string        `json:"name,omitempty"`
	PricePerSession *float64       `json:"price_per_session,omitempty"`
	Status          *ServiceStatus `json:"status,omitempty"`
	TrialPrice      *float64       `json:"trial_price,omitempty"`
}

// AssignCoachToServiceJSONBody defines parameters for AssignCoachToService.
type AssignCoachToServiceJSONBody struct {
	CoachId   int64 `json:"coach_id"`
	IsPrimary *bool `json:"is_primary,omitempty"`
}

// AddScheduleJSONBody defines parameters for AddSchedule.
type AddScheduleJSONBody struct {
	AvailableSlots int    `json:"available_slots"`
	CoachId        *int64 `json:"coach_id,omitempty"`
	DayOfWeek      int    `json:"day_of_week"`
	EndTime        string `json:"end_time"`
	StartTime      string `json:"start_time"`
}

// CompleteSessionJSONBody defines parameters for CompleteSession.
type CompleteSessionJSONBody struct {
	Attended   bool    `json:"attended"`
	CoachNotes *string `json:"coach_notes,omitempty"`
}

// RejectVendorJSONRequestBody defines body for RejectVendor for application/json ContentType.
type RejectVendorJSONRequestBody RejectVendorJSONBody

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody LoginUserJSONBody

// RegisterParentJSONRequestBody defines body for RegisterParent for application/json ContentType.
type RegisterParentJSONRequestBody RegisterParentJSONBody

// RegisterVendorJSONRequestBody defines body for RegisterVendor for application/json ContentType.
type RegisterVendorJSONRequestBody RegisterVendorJSONBody

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody CreateBookingJSONBody

// CancelBookingJSONRequestBody defines body for CancelBooking for application/json ContentType.
type CancelBookingJSONRequestBody CancelBookingJSONBody

// AddChildJSONRequestBody defines body for AddChild for application/json ContentType.
type AddChildJSONRequestBody AddChildJSONBody

// UpdateChildJSONRequestBody defines body for UpdateChild for application/json ContentType.
type UpdateChildJSONRequestBody UpdateChildJSONBody

// PaymentCallbackJSONRequestBody defines body for PaymentCallback for application/json ContentType.
type PaymentCallbackJSONRequestBody PaymentCallbackJSONBody

// CreateReviewJSONRequestBody defines body for CreateReview for application/json ContentType.
type CreateReviewJSONRequestBody CreateReviewJSONBody

// AddCoachJSONRequestBody defines body for AddCoach for application/json ContentType.
type AddCoachJSONRequestBody AddCoachJSONBody

// RespondToReviewJSONRequestBody defines body for RespondToReview for application/json ContentType.
type RespondToReviewJSONRequestBody RespondToReviewJSONBody

// AddScheduleExceptionJSONRequestBody defines body for AddScheduleException for application/json ContentType.
type AddScheduleExceptionJSONRequestBody AddScheduleExceptionJSONBody

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody CreateServiceJSONBody

// UpdateServiceJSONRequestBody defines body for UpdateService for application/json ContentType.
type UpdateServiceJSONRequestBody UpdateServiceJSONBody

// AssignCoachToServiceJSONRequestBody defines body for AssignCoachToService for application/json ContentType.
type AssignCoachToServiceJSONRequestBody AssignCoachToServiceJSONBody

// AddScheduleJSONRequestBody defines body for AddSchedule for application/json ContentType.
type AddScheduleJSONRequestBody AddScheduleJSONBody

// CompleteSessionJSONRequestBody defines body for CompleteSession for application/json ContentType.
type CompleteSessionJSONRequestBody CompleteSessionJSONBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9a3PbtpZ/hcO9H25nlMhp0ztdf3PspOvdxPHYTu50e70cmIQk1CTAAqBt3Yz/+w5e",
	"JCiCJEhRstPkk2UJr/PAwXnh4EsYkywnGGLOwsMvYQ4oyCCHVP53tITn4gvxOYEspijniODwMDxeoTQJ",
	"wBIGCAdrCCgLZyESv/xZQLoOZyEGGQwPQ7CE4Sxk8QpmQAzD17n4GmEOl5CGj4+z8A0htwgvLzngBSvn",
	"cw3GZJPaeH+jcBEehv8xr+CYq1/ZvDawnOoYcLgkdN0Glf45YGmxDP7O7lGWIbycBRngqxe84ITKfwHl",
	"LxIK7hFe/tACd6yHcgHPuBhGLUjg8TTphDoWbSKU1IZaEJoBrjD5j9fhzIXYY8TX3SMjXl9gAhegSMWw",
	"VwAvIQV4WQ1tLzsFjF2tc9g9vGgVyd72JBAXWXj4e5hTdAe4/C0DaRotKSnycBamgC6h/u/aOTsB8aoP",
	"aaLNGKSdAN4NVaLX3BxV/9Jc8AlY9wy5dmIoI1j9xAvI1Kd7mGDzma8Kqj8uKNKDAF5Q/bGQvZ0oPEHi",
	"n5h3L0s36uHhTUrkgK+qQSQJKPyzQBQm4SGnBRxKklP2DgqwYDfJEYsWup1rxTeEpBBgOeJ7lKFu2FPR",
	"wr03fjyYhRl4QJkg0qsD8R/C+j/n+j8QzFctIkf+JoTob7/99tuLDx8CjRC3VMlE60585oBzSEXX//vX",
	"v5Ivrx9fiD8/Pv7NyZjnYNnN7Pmm/C6x8KoX7HOwziDmZ0V2A2kXi+SqYYRly07wHCBAikg3Y+SySYug",
	"Myg1e85sM3gbzsofxQnn3kjnFMXwA3joXoBoFGXgoUVukOImtSSHxkM1PMI+wyM8ePgLwBFe9o1PZSuP",
	"Ccpd8bPFHAfOieEdgvfdkoPKNtEEAuQS0jsUw+7pmGo0zXyMIYL75pONJpnvFqXpe3gH0271STSLUtHO",
	"edzcwCXCWO5AMTrNYILUkQaSO4BjKVeBGYK5N8SnPCZCaepcSaEb9cnpzxAnhE6vGdrjho9iJkEAyPgb",
	"kiCodN8kkcrZhfpBfBUTzCGWH0GepygGQojP/2BCkn+xhTAlOaRcjyTUgogsohtE+cpDYZiFS4gTSPuA",
	"+FW1ejRI+NIcCKP4tvVHlsMYgTTCECbMLVwrtvxdTTLbgKZca8UL5OYPGHOF1fpZp1EZ5GCdEpAEnAQg",
	"SQIQSA23sQseZ5IIQpHbngg3iDiREIsmCz2KbIk4zFhzAMRYoWjSxHIbhuWx4TZ6NpBVfgEoBWvxP0wK",
	"tSjnyDADKHX/8iCOO4hjGCm7zDH/LFwUaRq1rjtfEdzJM+jfDnw1GtdB2mCnagUGGjPvdqwk2KWFlS7j",
	"FUyKFL59iKEcaHu2gmaoSO5ln81NIWBOqm4gaGPosuNW6GEaBUE5eg+utkcRuAMoBTcpjFhKeAs/luaa",
	"z4knhNBayCCppR1+qfSOfzj1DqsjxEnEUVanlPzCQSnGAeW+zTeoZ6+wNpK1hlkDN5PQ1klRxtASTyRL",
	"BxILsSinKAN0XdO8FyBlcOY69W08lnONRY0EXIkF8b/W8lw4OhYqTqqdRhNgSQ6XysaR76Z3dRoJuRoq",
	"AMGNgsgJMsnyFHKoFdYJNjvnQh9IXPqc2eWYcOihb5RDjYQ/A/Q20Ep2AFgQa1ideKAQcDgZ6TXGlevL",
	"z0l5JZoKFBlnn9/eGrgVc0Clod1CgZltBPmNqBHcpTkNk7laiA1egf8BvI1Yr01WG+q6V6drDGXZm5aP",
	"t8Y8FoLHigHJ2j1iQLZRNvl03O/PxBJ4iP8g6zbJoVwQtbP+524H1Mz4Dzh84E5evydFmkQUxiTLIE5a",
	"TFCbZBZk5ZK2JYtaZTtVtO9iAtG8VC4op/4lf0S4RTnTsYwBFK08/z3ir4wkhJtYc1AsKag6GTOEi7oI",
	"sybPwEOUA8pRjHKA2zTOduMHxLcCHa9+jKRjzcuXVnV7ParXL8N6SYdfDmmkpYNnP81iGaxjxRKNloeo",
	"h3CVz0lKOopAOgiG+xXg0b2aDlAv1ajiwlnpjbA4ZlYPODWYxYW3bXdvhzr5nizRFBZmq6WfA8buCZV7",
	"MkP4PcRLvgoPf+k7w0pr2/Qfg4QFoUHBIA1SAaYLfu3+PwZpegPi2+0xsaSEsQhkpMBugU5oAqkWUq5T",
	"nxcsikni3vacAsxALDlGexOdLNmLKQ13sAQc3oN1cA9vVoTcBrFGhAtXF3CJGJdREoj5BLYH4mvveO6s",
	"CvQNczX1OJF82bPd39THuLOaF2m890gws1KNAyopoSRHF6WUB3mCUzlJKGRuaXxTMIQhY+04Llt4WRq6",
	"cWlq/DWYRB0lDOT5RBy0ifhNNM9KomkcjmW5O8lDHiwnBp2K4Xw9Eds5H6hcs4bQDRTLCU6uyFRWB5UD",
	"MugDmW45Gja5dOld6lDfP+XCSJwohrSzCM8YBBQSsq64jYJ9MtOlzy5oFy8jFeVKAehUgRV8Jow4XAve",
	"Fv+t2qfkeMXlOpiZIawkCLuwNsr4iKbj2xwsES5DVl2IO69aPs5CJSTqHiSQph8X4eHvPmHc8HHW0H+k",
	"fp5EgDc8Qi/aPE9Cmx2ifo8LoTlI3vjm2uU6avaqhxs48JJnkhO0XGZBihgPSnn4OAvfACOsBrAJfABZ",
	"nsqWkFJCVRehZ4efj96fnhxdnX48i95eXHy8kCYbByhlkrgLBNMkPCzP5QwyBpai41vxTYBYUEIpqGza",
	"W+d31eVcfxlkBePBDQwAD1IIGA9+CeIVoCCWea2P13anzyBFiQQnWACUinkefbMITpTi9FbAXKLLgfM3",
	"IAl0fkEd2cqdpOIOKUx2tjON689xaC4KnFg2lZcTQfZptZF8pWczO7d3Y1iE+9Ibf/PcEHoZOlySwsRJ",
	"IiVP9kEgD5SdyB20dwQpHLjQoxY0IXaGIWErsJQ4ckHF3qNBYrAPqPJw84CuN3owFE6HrNfZ7giyfQNp",
	"8uyng7KCpQ6i0r73wpdyri0gkDcqGounED8FG2pgpiKPACEgC2UwUIjrcBIQr3YtYVVeUB/UstGE2pYc",
	"0Ck5jwlepCieSM06/nj27v3p8VVNH7pCGQxYSngAUgpBspYhwJ1oOAaaGojvCL1BSQLxNDC++3jx5vTk",
	"5O1ZDcijOIaMBQsz1w6AK+GoQXeKOaQYpMIIhLQ+yFZwnp5dvb04O3ofXb69+Pz2otSbK5jN1NL+gzRQ",
	"I0wPuHOeGhJ0jGNHe5aTW+g2+I2t1gXlJ6ZNbHvnyo4zPfL1ZPv8spBsuChSFQ+pIemM8HekwMk07HH2",
	"8Sp69/HT2UmNJS4gIwWNYYAJDxZith3ww5kZuwaejnd8gHxFkr2rErXZpzuwTBAnU1C5AFaGy86Yf5BN",
	"1mrgmYwF3XSH1toszAEa5nEx934UklviA7WrQd3r93G1bMUNaqoaM5h40F9ICO7CiLQEpB3ucKLSRDp2",
	"hFB/tBnXpN9tkjY06zH2jmdHdGkD3XcI3u9a79bxkR4MqrXsy6OhZnOq5SbtfddoKXO1+0IMpt2E0syM",
	"2YmA8o7ErjHRSd6pIS5vPbhhV+GUI5WUj1LE17s73svMf3FEMm9958j0OwEcOu8NGRC7UnInuazSn+46",
	"FfkUXQJgEcZFuJ1vWh1u8wsL7gIDHVy7Vx9sbc7twXL4YMvYsRDVzy9mqY41/21rDrjmfmVFZq7G9A9w",
	"qRvvgLU0RC4iqGj+X3lfqYi6c1+xSwhovHp2HKiR5s+CGp5/Ir4q4+a7FtksYBJ7G4iVqRjm7tEu+arM",
	"+fAxbXXrPSmherryWtIG83HAEeMoZvuS6OWEW5jJKeBCo5B2shqsDpQyTkZBNGpBv0IMKYoDpiauLeYT",
	"BgVfEYr+DSfyzH06O/p09V8fL07/923dOWdPFQC5lB1452qz2JCq3W7igPt20NVmn85Bp4Y1l5qYA2AZ",
	"e3mC2KaKIU0MZ6yAcYB5AtjqhgC6rzDnxqxbQ5aYkRywmVPkL3P47vLI1fg0S7PQWYoalQtYsyDHm4bl",
	"bf4WG9P/3r+j2IbvRbOW/DvXEb7ra6gDb5UOtp7LvJRRXv5tryR7Jwy0ULQ7W9L/AvOKcOJJ8FKziuxL",
	"yg4eHJEs6s+g8IHbycfbXI3e9UVnR0RHRV/8QkS1uNhbXGSWpHSVR9A5QFvxw4D9PyrONQs54SAdliGp",
	"unQzXRVZ2NjKvXd+vHGTkiUZmYG8kdnnn5Fd6XnNo7an9IBmNk8ua609MMTS6xe611Z92rZNvE3NC1tK",
	"DZE/gwSHN8eMuWU/XCrpDo3Dauxh6n9dQ07cFcKu7367Vi3EiSqeEBO8QDSTtfAIXhLzraai+GwyiR0F",
	"8soprvQ5bCaQV0fCWcgQXkqpUt4ntz7/EtrX093D25f8rPFNLeOIxStCUllTVpUzjmKIuYxUCpwzXiSI",
	"yAqACbpDSQHSSB3prtmOLSG+mW+XEhqt4IP7In/fRX/E8hSsI3mj180iKG7pu+3ZITTbYul5qBwb3ahR",
	"a2E6XWP39QO3R1nnNbQ2pW3MBTWr9vT2taR17ukOqgUuUAqjgrpvDj2zUoITFAwcUgusrNHsPC57eWVM",
	"6UH7hDAcA2KO7qAUdPrjtZdO7HTHNRV74xvclIot1QfKS1EdHAVTd47UkAh6EzPenm3TsDdrUsHuynf5",
	"tZRLZYVzIA+7BZQfXDv0vOaiqeNEFel28mveKoKldt7xUyS6Mt+9dl5prVvk78GHXGBvYPbck6TbmSZt",
	"wo116E7aDy8Iru7alZCH5l6ZU2vqQPyHEhjPndaqN7QKN5KPEDg5JQJU6XJB3jZq04S28FhgQfJQUb4b",
	"YSa7y4EXWWurXT/pL8W1U3eJsRI7VYmBpBhXO0ze8R8IZl/FMWX0Rx2lCnyrkjU4p54f4HDGQiqshgoX",
	"HlKpxgxRDqmwFDTr+FwUVWXjVd2Qm8Itwl+5+fBH99c/ub9+7f76Z2+FScp9K6ejOdYGWYZiwzXrpZUD",
	"+Lxd5wlYt2/J/dTi3Z8f/rLNYzm+gJ7aeXjpRuCTFsubTnP/XnZv/2X39lSnxLNaX9tWGupEroKlzluc",
	"cEypEBOWb5b1t4tT95+0105dD8XOuJzlqxvIzUP52LeujfIueoYxpEty7OmmT9Mor24AbJspqc/LAVH3",
	"Mnu+Odrgqx0ORqhvrE7nwixMKFhwp67ezMybYKvYCebrgRqzHZvzvccv1DyAYxjdZp78JUOj5TK9HJvT",
	"EM0OA9gucs0tSas/fxZiErEVuXeTsRLNkz6qY2cDOrQSyV+RSYRq0xWzDKmwixDfMPEk0ZKSe75qTThw",
	"cxOFdxAXsPXOmq+jNyd5kQIaxWVthw73WLteMdRsUcZAFz593Gr9o5g21pnW7pGisFWjKo0Xg3RvGDeJ",
	"0RjUqszlg4NPzgpaY/wFY6tuDckjaSkmSUn/rSwB6AVR54qfCiZ6dAUeyxFtv5mkenWD0Jh8QnIIU8Ml",
	"Kax5XMcRK1iuYtWdfm+TfzesXCnIIEZ8c5v2HjZ7qnLqCLzfQRqhDCzh2Bhlez1U/yQNwBEvEt+N25LT",
	"IX7AyyEDtW+A8S62CNwtJy2wWH+mbYhQ7fTl3EGKFqjNju2uJtvYufX85jGpefHAGPLgOKs7OW5wmp5r",
	"mIGO3aF5gWNr/joy2fwePvFWLJwZZk+U5vdsE2ra90uVP95AlhDL7tiFVnU7FSYdbOoREoPllYdUMVl/",
	"VWa4l964QixSz8w2WQ/eR3HBOMla9bQxat9g1VYs0bh3n+cKSQKcOUh+CcBjltg9onnftLPZkP3SlZHm",
	"1O5UAe62aCqDcUERX1+KnawPKggopEeFYkT13zuDjf/+55V5W1WelvLXCjkrznN1JQHhBWk+cn10fhok",
	"JC4yYYipWquEBnwFg/9BCQuOBABScwxMVUZzlexlcEwwhrHYrrpEPwvuEV8FfxZA3gOvHum33ufHSQAo",
	"D6RnHTIzG6JlAbqXYvGIC4U77FtD8CJ4A+JbiJPg6PxU6uNUyfnw1cuDlwcqRgwxyFF4GP708uDlTzJI",
	"y1cSsXOprc9ZzYZfQnkWCm6VCDlN5HU1bln68tACGZRFa9v8QFWTuf0Q9uP1RgHoHw8O2qR52W7uuHT4",
	"OAtfH7zq7+q8TSc7/9TfuVkoTqrf+lWCvt5dhdhsXpc4tLn892uBpvL+tUB/kDevMApOAUIW/W7sLjGq",
	"pqplIbeRVJfdHkzP5tvHj7N+JigfdPdobL2CP45hnGXFvzWWqdXSlqJpgVJJZA/GmX9ByeMc5Dkld0r5",
	"JMzBRkeqwWfjCBjGSafbSYWNW7tPR9/XB6/7ezaq7T0JY2iCmSJM1k1Ff65QR3g7U9jvgmzJE+bt83U7",
	"iqzn0eeuF0keJ+Mtj36OMvXf2dKDLS/sZ1l8uLLgq7l64auVDWUN0E+q1tlgTqo9kjaKheolSLflgulI",
	"UomCgq8g5gLRUD2ZBmQFTV5QrKsBBKoUn0UDQb06CUjBO2lACl4S4alF/P4ZWyGgQi/Cd+phB9iLW6rL",
	"Ds4tF1WLvLUfaQtHyU3XM29NtvdAfaPu5Haicwd8b1YYgADDe/O+GohjmRftQQ/rimQnPT7bj0yNokff",
	"STaAHhvFK587VcxJ0EUV2xvTZuSY6iKD9ZDajTtvy0VeuypVmP72n7Q/5pnaUc4HJ74+ISysoVRX+i8L",
	"sywIDeKCys1vCs9qHisZ61pG+117vPYw+5gt7nzZfdQOb3kK5klV1v/s79x4aOBJWOPYPJgrhE71ErmD",
	"E2yJI+0gD7HzZn2a7Nkqdr98sz1FvxpTQmz2m9obOiy4WQenJ55knau0qvbjXT2LVW39Pdq3tam3sk5a",
	"n/h6UrHx1TCZwlsA+kVGPUmsTV5UzwSNspMcLybtRksTmwukqSnmFMT2ug0GrC81DnRwoxMDps0o+F0v",
	"En3dekr5IpGtp5SZVyWqDdbaNZWjJDm2nkMdJG9M3630k/pbV08oX57A25okWrWQhApyShZIRW+bBLR3",
	"SqlgJDCFKt2iTtUT+b0h7Nftdv9qpL5Cug8tZ91y7gn0Qscu/Hb0QUWxNm2wLkQLB92sJ7P3q/A53up+",
	"nIj633W8HsZRuPeV3Lr8AJvHIE1vQHzbbkDoy/THpuEIvtgYYupY1w40R/NU0RJweA/WwT28WRFyG8QV",
	"FgxmDSo3MavfvOrSIutvfo3SJVueDduhPm1uGgV5/XEvD5R8qRfGeJxXCZI9KNKJW4OTeVTvMzndNueR",
	"+7Gyb8mEXMH4tiQ5M+RoobiV4dnlkNSXFEf7I1X/LQMOruebvim1/7K4yRAPgH67QppwLleBIaoiscnQ",
	"naunCVr3sHr3wZSgHryDzd1I/5gG4v6NT/TlE+8ORwPiGdVFRv/Fm8oE/hAAf2jPKYrhB4QHdgAP3h0u",
	"ZEL4kClO2TtdDuGZBpVa3i/ZzQGrJpE7sCxA3pILV2bIb2zHPl+/hucJbDr3C0vP4xisqTis9p5S0wLr",
	"Qv3cfl3Lgw72K2nj6dG/Dz4QzFcTUM/5qtszpmHtsTN1sskKiAsUB+q+iCddLZWmh6T6sa1dUvNJRODm",
	"I2LPkOrm9a0NQptbaa2kVvkbXika9WdgBhP5BHB/yo3L6tgvc7Q8i/Ntpq+X+RoWq6lfXmwE2jTHWZfw",
	"uhlOP8MTjifR5kM+3yiF4hKRGwQyP3THpnTpgFGxKdF3u9iUGOFZZc58PSxgBbc0DVvpb+3PxL5g271D",
	"q7u44/do8xWqb3SXVs9ZmZ836VWnkz7451907VClscnio12Zr7LBFSn9UMPOctVtyysgtSV8vwXyVd0C",
	"kbQLOCl9Zz1cakpjvai/Lt162jReER958jTG2eoU6n3b/PuJ5H0iseaT6n9fkRQlYD2PU8Jg8kPzpHIb",
	"L3bJhO6TarQz9iksi8bjhd/oicgqorWzQ3f+92VpBo+Mt5SOgG2kh/uR+e8yY3gCeNOt4SUgPLO1Km75",
	"fk3668j08uGHzpShaUg+KmmoV7T4+yk339n/rgfvJfNotDTSn6TNZvnDWrRixtASS0fIFRnLr7rfVmxr",
	"LWS78/CvYLU9gfIs0a98OcICa+U+p1vHzXy1yti9RtnTcF01/yQ23Hc1bHvTrYv72mSfKmcm2E8VHVSy",
	"T9VZ68ia0i3MG6rDOVD22+5SV30NWx7Ycgwz5Pcje1/8+wHQ20DzXgBYULJeZ9hK1/c0zFYvTveexCAN",
	"IL5DlOBM3fuRj5vJsnaH83kqGqwI44e/HBwczO9eSSdCfZBLDpYIL1uHYYfzOcjRC6bavbxFCQNlybmX",
	"Mcnc455TkhSxdK/0DN025HWJmUZVvqowiRo/yQnCXBjqquipKgLQXJS5BmaytYMMYLCEemW6b5m37UBW",
	"41Zb8PfLsozfB8BXs+CI8h+swaqrbu3DJYjJms5rWQHEvKhYjlFKtOYIpuKfC46SjxzE0Uml1VtvVbcy",
	"r7TZTacjqDIwMu/MWqXJ1mh2U14la40uimnnbWtvk13ignRT8rcOonSXjiGM6tI6wk0Hwjf3b3MQWXYu",
	"yAGGqZNrZQGjx+vH/w8AAP//dPQ7t93SAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
